=== Pageboy/shakespeare_repo/resources/shakespeare_play.dtd
<!ELEMENT shakespeareplay (dramatis,play)>
<!ELEMENT dramatis (dramatis_head,dramatis_personae,play_location)>
<!ELEMENT dramatis_personae ((charactername+,character_role+)*)>
<!ELEMENT charactername (#PCDATA)>
<!ELEMENT character_role (#PCDATA)>
<!ELEMENT play ((act,(((firstscene|scene)+,location?,(stage_directions|character|prose|verseline)+))*)*)>
<!ELEMENT location (#PCDATA | scene_image)*>
<!ELEMENT dramatis_head (#PCDATA)>
<!ELEMENT play_location (#PCDATA)>
<!ELEMENT act (#PCDATA)>
<!ELEMENT firstscene (#PCDATA)>
<!ELEMENT scene (#PCDATA)>
<!ELEMENT stage_directions (#PCDATA)>
<!ELEMENT character (#PCDATA)>
<!ELEMENT prose (#PCDATA)>
<!ELEMENT verseline (#PCDATA)>
<!ELEMENT scene_image (#PCDATA)>
<!ATTLIST scene_image href CDATA #REQUIRED>
<!ATTLIST shakespeareplay title CDATA #REQUIRED>

=== Pageboy/shakespeare_repo/text_of_plays/macbeth.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shakespeareplay SYSTEM "shakespeare_play.dtd" []>
<shakespeareplay title="Macbeth">
<dramatis_personae>
<dramatis_head>Dramatis Personae</dramatis_head>
<charactername>Duncan, <character_role>King of Scotland</character_role>
</charactername>
<charactername>Macbeth, <character_role>Thane of Glamis and Cawdor, a general in the King&#8217;s army</character_role></charactername>
<charactername>Lady Macbeth, <character_role>his wife</character_role></charactername>
<charactername>Macduff, Thane of Fife,<character_role> a nobleman of Scotland</character_role></charactername>
<charactername>Lady Macduff, <character_role>his wife</character_role></charactername>
<charactername>Malcolm, <character_role>elder son of Duncan</character_role></charactername>
<charactername>Donalbain, <character_role>younger son of Duncan</character_role></charactername>
<charactername>Banquo, <character_role>Thane of Lochaber, a general in the King&#8217;s army</character_role></charactername>
<charactername>Fleance, <character_role>his son</character_role></charactername>
<charactername>Lennox, <character_role>nobleman of Scotland</character_role></charactername>
<charactername>Ross, <character_role>nobleman of Scotland</character_role></charactername>
<charactername>Menteith <character_role>nobleman of Scotland</character_role></charactername>
<charactername>Angus, <character_role>nobleman of Scotland</character_role></charactername>
<charactername>Caithness, <character_role>nobleman of Scotland</character_role></charactername>
<charactername>Siward, Earl of Northumberland, <character_role>general of the English forces</character_role></charactername>
<charactername>Young Siward, <character_role>his son</character_role></charactername>
<charactername>Seyton, <character_role>attendant to Macbeth</character_role></charactername>
<charactername>Hecate, <character_role>Queen of the Witches</character_role></charactername>
<charactername>The Three Witches</charactername>
<charactername>Boy, Son of Macduff</charactername>
<charactername>Gentlewoman attending on Lady Macbeth</charactername>
<charactername>An English Doctor</charactername>
<charactername>A Scottish Doctor</charactername>
<charactername>A Sergeant</charactername>
<charactername>A Porter</charactername>
<charactername>An Old Man</charactername>
<charactername>The Ghost of Banquo and other Apparitions</charactername>
<charactername>Lords, Gentlemen, Officers, Soldiers, Murtherers, Attendants, and Messengers</charactername>
<play_location>Scene: Scotland and England</play_location>
</dramatis_personae>
<play>
<act>Act I</act>
<firstscene>Scene I</firstscene>
<location>A desert place. Thunder and lightning</location>
<stage_directions>Enter three Witches</stage_directions>
<character>First Witch</character>
<verseline>When shall we three meet again?</verseline>
<verseline>In thunder, lightning, or in rain?</verseline>
<character>Second Witch</character>
<verseline>When the hurlyburly&#8217;s done,</verseline>
<verseline>When the battle&#8217;s lost and won</verseline>
<character>Third Witch</character>
<verseline>That will be ere the set of sun</verseline>
<character>First Witch</character>
<verseline>Where the place?</verseline>
<character>Second Witch</character>
<verseline>Upon the heath</verseline>
<character>Third Witch</character>
<verseline>There to meet with Macbeth</verseline>
<character>First Witch</character>
<verseline>I come, Graymalkin</verseline>
<character>All</character>
<verseline>Paddock calls. Anon!</verseline>
<verseline>Fair is foul, and foul is fair</verseline>
<verseline>Hover through the fog and filthy air</verseline>
<stage_directions> Exeunt</stage_directions>
<scene>Scene II</scene>
<location>A camp near Forres. Alarum within</location>
<stage_directions>Enter Duncan, Malcolm, Donalbain, Lennox, with Attendants, meeting a bleeding Sergeant</stage_directions>
<character>Duncan</character>
<verseline>What bloody man is that? He can report,</verseline>
<verseline>As seemeth by his plight, of the revolt</verseline>
<verseline>The newest state</verseline>
<character>Malcolm</character>
<verseline>This is the sergeant</verseline>
<verseline>Who like a good and hardy soldier fought</verseline>
<verseline>&#8216;Gainst my captivity. Hail, brave friend!</verseline>
<verseline>Say to the King the knowledge of the broil</verseline>
<verseline>As thou didst leave it</verseline>
<character>Sergeant</character>
<verseline>Doubtful it stood,</verseline>
<verseline>As two spent swimmers that do cling together</verseline>
<verseline>And choke their art. The merciless Macdonwald-</verseline>
<verseline>Worthy to be a rebel, for to that</verseline>
<verseline>The multiplying villainies of nature</verseline>
<verseline>Do swarm upon him -from the Western Isles</verseline>
<verseline>Of kerns and gallowglasses is supplied;</verseline>
<verseline>And Fortune, on his damned quarrel smiling,</verseline>
<verseline>Show&#8217;d like a rebel&#8217;s whore. But all&#8217;s too weak;</verseline>
<verseline>For brave Macbeth -well he deserves that name-</verseline>
<verseline>Disdaining Fortune, with his brandish&#8217;d steel,</verseline>
<verseline>Which smoked with bloody execution,</verseline>
<verseline>Like Valor&#8217;s minion carved out his passage</verseline>
<verseline>Till he faced the slave,</verseline>
<verseline>Which ne&#8217;er shook hands, nor bade farewell to him,</verseline>
<verseline>Till he unseam&#8217;d him from the nave to the chaps,</verseline>
<verseline>And fix&#8217;d his head upon our battlements</verseline>
<character>Duncan</character>
<verseline>O valiant cousin! Worthy gentleman!</verseline>
<character>Sergeant</character>
<verseline>As whence the sun &#8216;gins his reflection</verseline>
<verseline>Shipwrecking storms and direful thunders break,</verseline>
<verseline>So from that spring whence comfort seem&#8217;d to come</verseline>
<verseline>Discomfort swells. Mark, King of Scotland, mark</verseline>
<verseline>No sooner justice had, with valor arm&#8217;d,</verseline>
<verseline>Compell&#8217;d these skipping kerns to trust their heels,</verseline>
<verseline>But the Norweyan lord, surveying vantage,</verseline>
<verseline>With furbish&#8217;d arms and new supplies of men,</verseline>
<verseline>Began a fresh assault</verseline>
<character>Duncan</character>
<verseline>Dismay&#8217;d not this</verseline>
<verseline>Our captains, Macbeth and Banquo.?</verseline>
<character>Sergeant</character>
<verseline>Yes,</verseline>
<verseline>As sparrows eagles, or the hare the lion</verseline>
<verseline>If I say sooth, I must report they were</verseline>
<verseline>As cannons overcharged with double cracks,</verseline>
<verseline>So they</verseline>
<verseline>Doubly redoubled strokes upon the foe</verseline>
<verseline>Except they meant to bathe in reeking wounds,</verseline>
<verseline>Or memorize another Golgotha,</verseline>
<verseline>I cannot tell-</verseline>
<verseline>But I am faint; my gashes cry for help</verseline>
<character>Duncan</character>
<verseline>So well thy words become thee as thy wounds;</verseline>
<verseline>They smack of honor both. Go get him surgeons. </verseline>
<verseline>
<stage_directions_inline> Exit Sergeant, attended.</stage_directions_inline>
</verseline>
<verseline>Who comes here?</verseline>
<stage_directions>Enter Ross</stage_directions>
<character>Malcolm</character>
<verseline>The worthy Thane of Ross</verseline>
<character>Lennox</character>
<verseline>What a haste looks through his eyes! So should he look</verseline>
<verseline>That seems to speak things strange</verseline>
<character>Ross</character>
<verseline>God save the King!</verseline>
<character>Duncan</character>
<verseline>Whence camest thou, worthy Thane?</verseline>
<character>Ross</character>
<verseline>From Fife, great King,</verseline>
<verseline>Where the Norweyan banners flout the sky</verseline>
<verseline>And fan our people cold</verseline>
<verseline>Norway himself, with terrible numbers,</verseline>
<verseline>Assisted by that most disloyal traitor</verseline>
<verseline>The Thane of Cawdor, began a dismal conflict,</verseline>
<verseline>Till that Bellona&#8217;s bridegroom, lapp&#8217;d in proof,</verseline>
<verseline>Confronted him with self-comparisons,</verseline>
<verseline>Point against point rebellious, arm &#8216;gainst arm,</verseline>
<verseline>Curbing his lavish spirit; and, to conclude,</verseline>
<verseline>The victory fell on us</verseline>
<character>Duncan</character>
<verseline>Great happiness!</verseline>
<character>Ross</character>
<verseline>That now</verseline>
<verseline>Sweno, the Norways&#8217; king, craves composition;</verseline>
<verseline>Nor would we deign him burial of his men</verseline>
<verseline>Till he disbursed, at Saint Colme&#8217;s Inch,</verseline>
<verseline>Ten thousand dollars to our general use</verseline>
<character>Duncan</character>
<verseline>No more that Thane of Cawdor shall deceive</verseline>
<verseline>Our bosom interest. Go pronounce his present death,</verseline>
<verseline>And with his former title greet Macbeth</verseline>
<character>Ross</character>
<verseline>I&#8217;ll see it done</verseline>
<character>Duncan</character>
<verseline>What he hath lost, noble Macbeth hath won</verseline>
<stage_directions> Exeunt</stage_directions>
<scene>Scene III</scene>
<location>A heath. Thunder</location>
<stage_directions>Enter the three Witches</stage_directions>
<character>First Witch</character>
<verseline>Where hast thou been, sister?</verseline>
<character>Second Witch</character>
<verseline>Killing swine</verseline>
<character>Third Witch</character>
<verseline>Sister, where thou?</verseline>
<character>First Witch</character>
